### ISSUE TITLE
Switch version crashes on startup

### ISSUE THREAD

**Issue by Devnol** [AGORI-Studios/Rit#15]
The switch build of rit (downloaded from hbappstore) crashes on boot at
```lua
lib/ini.lua:27: attempt to index a nil value

[love "callbacks.lua"]:228: in function 'handler'
lib/ini.lua:27: in function 'load'
settings.lua:106: in function 'loadSettings'
main.lua:291: in function 'load'
[love "callbacks.lua"]:136: in function <[love "callbacks.lua"]:135>
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```
/switch/rit/settings.ini does exist btw

**Comment by GuglioIsStupid** [comment]
Weird, so it seems like it doesnt make the file on startup,,, im gonna have to investigate this after school 
In the meantime, try launching the game again, it sometimes fixes that problem

**Comment by Devnol** [comment]
But the file already exists. Unless the path is wrong or something like that. Also you should probably clarify somewhere where exactly beatmaps should go.
I tried launching the game again and again, I even redownloaded it from the github, nothing changed.

**Comment by GuglioIsStupid** [comment]
Just tested HB Appstore version now

It creates the settings.ini file but Rit can't access it because of the file structure (Due to how FTU packages Rit on HBAppstore) I'm gonna have to mention that to then in their discord, i can't really do anything about it rn, you'll just have to move the files manually for now

**Comment by Devnol** [comment]
Oh alright, where to?

**Comment by GuglioIsStupid** [comment]
I just uploaded a new version, its not on the HBAppstore currently but you can download the release

**Comment by Devnol** [comment]
Hey I downloaded Rit.nro from releases into /switch/Rit.nro and when I start it I get the Love nogame screen (a duck balloon thing)

**Comment by GuglioIsStupid** [comment]
> Hey I downloaded Rit.nro from releases into /switch/Rit.nro and when I start it I get the Love nogame screen (a duck balloon thing)

Thats weirddd, i think im fusing the game.love wrong....
It'll be a bit before i can fix it tho

**Comment by Devnol** [comment]
That's okay, no need to hurry. Thanks for your time anyway.

**Comment by GuglioIsStupid** [comment]
Try https://github.com/GuglioIsStupid/Rit/releases/tag/v0.0.5-svimprovement

**Comment by Devnol** [comment]
Tried again, when launched without a rit folder under sdmc:/switch/ it says "songs folder created under at sdmc:/switch/rit/songs" in a white rectangle in the middle of the screen, and then I can do nothing but exit. I put an osz in /switch/rit/songs/osu, and it says the folder structure is outdated. Then, I move the song to just /switch/rit/songs and open the game again, black screen with nothing to do.

**Comment by GuglioIsStupid** [comment]
thats rly weird cuz when I run that exact version it has default songs included with it...

loading times is really long right now tho so just wait a while

**Comment by FlipsSimple** [comment]
after waiting for it to load, it goes back to hbmenu. when i try to launch it again the same result occurs

**Comment by GuglioIsStupid** [comment]
Due to rewrite, this will now be closed.

Switch support continuation is now unknown.
