### ISSUE TITLE
PC version launches, but does not start.

### ISSUE THREAD

**Issue by Lunarspheal6** [AGORI-Studios/Rit#17]
Program returns the following error:

main.lua:175: attempt to index global 'song' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
main.lua:175: in function 'load'
[love "callbacks.lua"]:136: in function <[love "callbacks.lua"]:135>
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by GuglioIsStupid** [comment]
Did you download the latest noghtly build? https://nightly.link/GuglioIsStupid/Rit/workflows/windows-build.yaml/master

**Comment by Lunarspheal6** [comment]
Yep. Same error.

**Comment by GuglioIsStupid** [comment]
Try downloading some songs into %appdata%\Rit\songs 
And if theres a "packs" folder there, delete it

**Comment by GuglioIsStupid** [comment]
Due to rewrite, this will now be closed.
